#!/usr/bin/env python3
"""Synchronize shared workspace credentials into subproject env files.

The root `.env` remains the source of truth. This script copies only approved
shared keys into each subproject `.env.local`, preserving any existing
project-specific variables and never printing secret values.
"""

from __future__ import annotations

import argparse
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
ROOT_ENV_FILE = WORKSPACE_ROOT / ".env"
TARGET_ENV_FILE = ".env.local"

SHARED_ENV_KEYS = (
    "NZ_LEGISLATION_API_KEY",
    "HF_TOKEN",
    "ZENODO_TOKEN",
)

SUBPROJECTS = (
    "cli-legislation-nz",
    "corpus-law-nz",
    "corpus-nz-hansard",
    "corpus-cases-medilegal-nz",
    "hathi-nz",
    "nlp-policy-nz",
    "sm-govt-nz",
)


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a simple dotenv file into a mapping."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        values[name.strip()] = value.strip().strip('"').strip("'")
    return values


def render_env_file(values: dict[str, str]) -> str:
    """Render dotenv values with stable ordering."""
    lines = [
        "# Generated by scripts/sync_workspace_env.py.",
        "# Do not commit this file. It contains local credentials.",
    ]
    for name in sorted(values):
        lines.append(f"{name}={values[name]}")
    return "\n".join(lines) + "\n"


def sync_workspace_env(
    workspace_root: Path = WORKSPACE_ROOT,
    root_env_file: Path = ROOT_ENV_FILE,
    dry_run: bool = False,
) -> list[Path]:
    """Copy shared root env keys into each subproject `.env.local`."""
    root_values = parse_env_file(root_env_file)
    missing = [name for name in SHARED_ENV_KEYS if not root_values.get(name)]
    if missing:
        raise SystemExit(
            "Root .env is missing required shared keys: " + ", ".join(missing)
        )

    shared_values = {name: root_values[name] for name in SHARED_ENV_KEYS}
    updated: list[Path] = []

    for subproject in SUBPROJECTS:
        subproject_dir = workspace_root / subproject
        if not subproject_dir.is_dir():
            continue
        target = subproject_dir / TARGET_ENV_FILE
        current_values = parse_env_file(target)
        merged = {**current_values, **shared_values}
        rendered = render_env_file(merged)
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            continue
        updated.append(target)
        if not dry_run:
            target.write_text(rendered, encoding="utf-8")

    return updated


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    updated = sync_workspace_env(dry_run=args.dry_run)
    action = "Would update" if args.dry_run else "Updated"
    for target in updated:
        print(f"{action}: {target.relative_to(WORKSPACE_ROOT)}")
    if not updated:
        print("No env sync changes needed.")
    print(f"Checked {len(SUBPROJECTS)} subprojects for {len(SHARED_ENV_KEYS)} shared keys.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
